ae_compta_homepage:
    path:     /hello/{name}
    defaults: { _controller: AEComptaBundle:Default:index }

ae_compta_simulation_save:
    path:     /simulation
    defaults: { _controller: AEComptaBundle:Simulation:saveImpotsMensuels }
