a_eplatform_homepage:
    path:     /hello
    defaults: { _controller: AEplatformBundle:Default:index }

page_d_accueil:
    path:    /homepage
    defaults: {_controller: AEplatformBundle:Advert:homepage }

page_faq:
    path:   /faq
    defaults: {_controller: AEplatformBundle:Advert:faq}

dashboard_user:
    path:   /dashboard
    defaults: {_controller: AEplatformBundle:Dashboard:dashboard}

entreprise_user:
    path:   /mon-entreprise
    defaults: {_controller: AEplatformBundle:Entreprise:newEntreprise}