ae_compta_homepage:
    path:     /hello/{name}
    defaults: { _controller: AEComptaBundle:Default:index }

ae_compta_recettes:
    resource: "@AEComptaBundle/Resources/config/routing/recettes.yml"
    prefix:   /recettes

ae_compta_achats:
    resource: "@AEComptaBundle/Resources/config/routing/achats.yml"
    prefix:   /achats

ae_compta_factures:
    resource: "@AEComptaBundle/Resources/config/routing/factures.yml"
    prefix:   /factures